import "./globals.css";
import { Inter, Roboto } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["400", "700", "500"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ContextProvider from "@/store/ContextProvider";
import Footer from "@/components/Footer/Footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable}`}>
        <div className=" min-h-screen">{/* para que las altura minima de las paginas sea el total de la pantalla */}
          <ContextProvider>{children}</ContextProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
